# Assignment-5
## UCS420 "Cognitive Computing"
### NumPy - Introduction-1

Name: **Aarav K. Arora**
Roll No. : "1024160106"

## Q1. Create a NumPy 1D array with 5 elements and perform basic operations
a) Addition of 2 to all elements
b) Multiply 3 with all elements
c) Divide every element by 2

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print("Original array:", arr1)

add_result = arr1 + 2
print("After adding 2:", add_result)

mul_result = arr1 * 3
print("After multiplying by 3:", mul_result)

div_result = arr1 / 2
print("After dividing by 2:", div_result)


Original array: [1 2 3 4 5]
After adding 2: [3 4 5 6 7]
After multiplying by 3: [ 3  6  9 12 15]
After dividing by 2: [0.5 1.  1.5 2.  2.5]


## Q2. Questions on Basic NumPy Array

### a) Reverse the NumPy array: `arr = np.array([1, 2, 3, 6, 4, 5])`

In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", reversed_arr)


Error: No connection selected.

### b) Find the most frequent value and its indices
i. `x = np.array([1,2,3,4,5,1,2,1,1,1])`
ii. `y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])`

In [ ]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

def most_frequent_with_indices(a):
    values, counts = np.unique(a, return_counts=True)
    max_count = counts.max()
    most_frequent_value = values[np.argmax(counts)]
    indices = np.where(a == most_frequent_value)[0]
    return most_frequent_value, max_count, indices

val_x, count_x, idx_x = most_frequent_with_indices(x)
print(f"x -> Most frequent value: {val_x} (occurs {count_x} times), Indices: {idx_x}")

val_y, count_y, idx_y = most_frequent_with_indices(y)
print(f"y -> Most frequent value: {val_y} (occurs {count_y} times), Indices: {idx_y}")


x -> Most frequent value: 1 (occurs 5 times), Indices: [0 5 7 8 9]
y -> Most frequent value: 1 (occurs 3 times), Indices: [0 1 2]


## Q3. 2-D Array Indexing
`arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])`
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [ ]:
arr_2d = np.array([[10, 20, 30],
                    [40, 50, 60],
                    [70, 80, 90]])
print("2-D array:\n", arr_2d)

# a) 1st row, 2nd column (1-based -> index [0, 1])
a_val = arr_2d[0, 1]
print("a) 1st row, 2nd column:", a_val)

# b) 3rd row, 1st column (1-based -> index [2, 0])
b_val = arr_2d[2, 0]
print("b) 3rd row, 1st column:", b_val)


2-D array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
a) 1st row, 2nd column: 20
b) 3rd row, 1st column: 70


## Q4. `linspace()`, Array Attributes, and Transpose

Create a 1-D NumPy array named `Aarav` with 25 evenly spaced numbers from 10 to 100 using
`linspace()`. Print its dimensions, shape, total elements, data type, and total bytes consumed.
Then find its transpose using the `reshape()` attribute, and check whether the `.T` attribute
achieves the same result.

In [ ]:
Aarav = np.linspace(10, 100, 25)
print("Array Aarav:\n", Aarav)

print("\nDimensions (ndim):", Aarav.ndim)
print("Shape:", Aarav.shape)
print("Total elements (size):", Aarav.size)
print("Data type (dtype):", Aarav.dtype)
print("Total bytes consumed (nbytes):", Aarav.nbytes)


Array Aarav:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type (dtype): float64
Total bytes consumed (nbytes): 200


In [ ]:
# Transpose using reshape(): a 1-D array has only one axis, so a "true" transpose
# has no visible effect. To actually reshape it into a transposed-looking form,
# we convert it into a 2-D column vector using reshape().
Aarav_reshape_transpose = Aarav.reshape(25, 1)
print("Shape after reshape(25, 1) [acts like a transpose - row vector to column vector]:")
print(Aarav_reshape_transpose.shape)
print(Aarav_reshape_transpose[:5])  # preview first 5 rows


Shape after reshape(25, 1) [acts like a transpose - row vector to column vector]:
(25, 1)
[[10.  ]
 [13.75]
 [17.5 ]
 [21.25]
 [25.  ]]


**Can we do the same with the `.T` attribute?**

No — not for a 1-D array. The `.T` attribute swaps axes, but a 1-D array only has a single axis,
so `.T` on `Aarav` returns the exact same 1-D array unchanged (shape stays `(25,)`).
`.T` only produces a *visible* transpose effect on arrays with 2 or more dimensions
(e.g. it would work on `Aarav_reshape_transpose` above, turning `(25, 1)` back into `(1, 25)`).

In [ ]:
print("Aarav.T shape (no change for 1-D array):", Aarav.T.shape)
print("Are Aarav and Aarav.T identical?", np.array_equal(Aarav, Aarav.T))

# .T DOES work as expected once the array is 2-D:
print("\nAarav_reshape_transpose shape:", Aarav_reshape_transpose.shape)
print("Aarav_reshape_transpose.T shape:", Aarav_reshape_transpose.T.shape)


Aarav.T shape (no change for 1-D array): (25,)
Are Aarav and Aarav.T identical? True

Aarav_reshape_transpose shape: (25, 1)
Aarav_reshape_transpose.T shape: (1, 25)


## Q5. 2-D Array: Statistics, Reshape, and Resize

Create a 2-D array of 3 rows and 4 columns, named `ucs420_aarav`, with values:
10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35.
Compute mean, median, max, min, and unique elements. Reshape it to 4 rows x 3 columns as
`reshaped_ucs420_aarav`. Resize it to 2 rows x 3 columns as `resized_ucs420_aarav`.

In [ ]:
ucs420_aarav = np.array([[10, 20, 30, 40],
                          [50, 60, 70, 80],
                          [90, 15, 20, 35]])
print("ucs420_aarav (3x4):\n", ucs420_aarav)


ucs420_aarav (3x4):
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]


In [ ]:
mean_val = np.mean(ucs420_aarav)
median_val = np.median(ucs420_aarav)
max_val = np.max(ucs420_aarav)
min_val = np.min(ucs420_aarav)
unique_vals = np.unique(ucs420_aarav)

print("Mean:", mean_val)
print("Median:", median_val)
print("Max:", max_val)
print("Min:", min_val)
print("Unique elements:", unique_vals)


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]


In [ ]:
# Reshape to 4 rows x 3 columns
reshaped_ucs420_aarav = ucs420_aarav.reshape(4, 3)
print("reshaped_ucs420_aarav (4x3):\n", reshaped_ucs420_aarav)


reshaped_ucs420_aarav (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [ ]:
# Resize to 2 rows x 3 columns (6 elements total - fewer than the original 12,
# so np.resize() takes the first 6 elements in row-major order)
resized_ucs420_aarav = np.resize(ucs420_aarav, (2, 3))
print("resized_ucs420_aarav (2x3):\n", resized_ucs420_aarav)


resized_ucs420_aarav (2x3):
 [[10 20 30]
 [40 50 60]]
